create table
    user_roles (
        user_id bigint not null,
        role varchar(255) check (
            (
                role in ('ADMIN', 'FLEET_MANAGER', 'DRIVER', 'REQUESTER')
            )
        )
    );

create table
    users (
        id bigint generated by default as identity,
        first_access_token varchar(255),
        name varchar(255) not null,
        password varchar(255),
        registration varchar(255) not null unique,
        status varchar(255) not null check ((status in ('FIRST_ACESS', 'ACTIVE', 'INACTIVE'))),
        primary key (id)
    );

create table
    vehicle (
        capacity integer,
        current_mileage integer,
        id bigint generated by default as identity,
        license_plate varchar(255),
        make varchar(255),
        model varchar(255),
        status varchar(255) check ((status in ('ACTIVE', 'INACTIVE'))),
        type varchar(255) check (
            (
                type in ('PICKUP', 'SUV', 'SEDAN', 'HATCH', 'MOTORCYCLE')
            )
        ),
        primary key (id)
    );

create table
    vehicle_mileage_entry (
        mileage integer,
        source smallint check ((source between 0 and 3)),
        id bigint generated by default as identity,
        recorded_at timestamp(6),
        recorded_by bigint,
        vehicle_id bigint not null,
        obs varchar(255),
        primary key (id)
    );

create table
    vehicle_request (
        purpose smallint check ((purpose between 0 and 3)),
        created_at timestamp(6),
        driver_id bigint,
        end_date_time timestamp(6),
        id bigint generated by default as identity,
        requester_id bigint not null,
        start_date_time timestamp(6),
        vehicle_id bigint,
        priority varchar(255) check ((priority in ('LOW', 'NORMAL', 'HIGH', 'URGENT'))),
        process_number varchar(255),
        status varchar(255) check (
            (
                status in (
                    'SENT_TO_MANAGER',
                    'APPROVED',
                    'REJECTED',
                    'IN_USE',
                    'FINISHED',
                    'CANCELED'
                )
            )
        ),
        primary key (id)
    );

create table
    vehicle_request_history (
        action smallint check ((action between 0 and 3)),
        id bigint generated by default as identity,
        performed_at timestamp(6),
        performed_by bigint not null,
        vehicle_request_id bigint not null,
        notes varchar(255),
        primary key (id)
    );

create table
    vehicle_usage (
        mileage_end integer,
        mileage_start integer,
        status smallint check ((status between 0 and 3)),
        check_in_at timestamp(6),
        check_out_at timestamp(6),
        driver_id bigint not null,
        id bigint generated by default as identity,
        vehicle_request_id bigint not null unique,
        primary key (id)
    );

alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;

alter table if exists vehicle_mileage_entry add constraint FKqb54rkri0qvm0vu2basdcpa2t foreign key (recorded_by) references users;

alter table if exists vehicle_mileage_entry add constraint FKj4tr7sjs1patgopw8y2eov1lx foreign key (vehicle_id) references vehicle;

alter table if exists vehicle_request add constraint FKhbtdudfosyv6wy9w7fjthvxp1 foreign key (driver_id) references users;

alter table if exists vehicle_request add constraint FKn0t20gkdq3hynrswv687ji13g foreign key (requester_id) references users;

alter table if exists vehicle_request add constraint FK8xriroeg21nr7n3hpoc72v8he foreign key (vehicle_id) references vehicle;

alter table if exists vehicle_request_history add constraint FKbd5u6r1pom1emqthuo78vf9vy foreign key (performed_by) references users;

alter table if exists vehicle_request_history add constraint FKqnsujtcjgfoc0tf6dylqjr3jn foreign key (vehicle_request_id) references vehicle_request;

alter table if exists vehicle_usage add constraint FKls52jfsrc0hr8lwml9ysq7aen foreign key (driver_id) references users;

alter table if exists vehicle_usage add constraint FKfdkyb97ef8d70d64mjq6c57l6 foreign key (vehicle_request_id) references vehicle_request;